stages:
    - deploy

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main

