name: Run the integration tests

on:
    push:
        branches:
            - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        steps:
            # Checkout the Repo
            - uses: actions/checkout@v2

            # Install Node 16
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            # Install dependencies
            - run: npm install

            # Run tests
            - run: npm test
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout the Repo
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                branch: "main"
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "share-a-meal-avans"
                heroku_email: "dierckx24@hotmail.com"